# This is a generated file. Not intended for manual editing.
services:
  orderprocessingservice:
    build:
      context: "/Users/yakov/git/Technical-task-Entravel/TechnicalTaskEntravel"
      dockerfile: "OrderProcessingService/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57421"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "orderprocessingservice:dev"
    ports:
    - "127.0.0.1:57021:57000"
    - "127.0.0.1:57221:57200"
    - "127.0.0.1:57421:57421"
    volumes:
    - "/Users/yakov/git/Technical-task-Entravel/TechnicalTaskEntravel/OrderProcessingService:/app:rw"
    - "/Users/yakov/git/Technical-task-Entravel/TechnicalTaskEntravel:/src:rw"
    - "/Users/yakov/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/yakov/.local/share/JetBrains/RiderRemoteDebugger/2025.2.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Users/yakov/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/yakov/Library/Logs/JetBrains/Rider2025.2/DebuggerWorker/JetBrains.Debugger.Worker.2025_10_17_12_46_04:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
